site_name: V5 Debugger
repo_url: https://github.com/Interfiber/v5dbg
repo_name: Interfiber/v5dbg
site_url: https://v5dbg.beachmont.xyz
copyright: Copyright &copy; 2025 Hunter Stasonis

nav:
  - Home: index.md
  - Getting Started:
    - Installation: install/server.md
    - Integration: getting_started/integration.md
  - C++ Documentation:
    - Header files: cpp/header_files.md
    - Macros:
      - $function: cpp/macros/debug/function.md
      - $ntask: cpp/macros/debug/ntask.md
      - $expose: cpp/macros/debug/expose.md
  - Debugger:
    - Installation: install/debugger.md
    - Commands:
      - suspend: debugger/cmds/suspend.md
      - resume: debugger/cmds/resume.md
      - backtrace: debugger/cmds/backtrace.md
      - frame: debugger/cmds/frame.md
      - mem: debugger/cmds/mem.md
      - print: debugger/cmds/print.md
      - state: debugger/cmds/state.md
      - thread: debugger/cmds/thread.md
  # - Advanced Topics:
    # - Pretty Printers: advanced/pretty_printers.md
    # - Wireless Debugging: advanced/wireless.md
  - Engineering:
    - Debug Server:
      - Stack traces: debug_server/stack.md
      - Exposed memory: debug_server/exposed_memory.md
    # - Debugger:
      # - Comms server: debugger/comms.md
    - Protocol Documentation: protocol/v1.md

theme:
  name: material
  font:
    code: JetBrains Mono
  icon:
    logo: material/bug
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.path
    - content.code.copy
    - navigation.top
    - navigation.instant
    - content.code.annotate
    - toc.integrate
    - navigation.footer
    - content.tooltips
    - navigation.tracking
    - navigation.expand

plugins:
  - social:
      cards_layout_dir: layouts
      cards_layout: custom
      debug: true
  - search

markdown_extensions:
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbr.md 
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Interfiber/v5dbg
      name: v5dbg on GitHub

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css