site_name: V5 Debugger
repo_url: https://github.com/Interfiber/v5dbg
repo_name: Interfiber/v5dbg

nav:
  - Home: index.md
  - Getting Started:
    - Installation: install/server.md
    - Integration: getting_started/integration.md
  - C++ Documentation:
    - Header files: cpp/header_files.md
    - Macros:
      - Debug macros:
        - $function: cpp/macros/debug/function.md
        - $ntask: cpp/macros/debug/ntask.md
  - Debugger:
    - Installation: install/debugger.md
    - Commands:
      - suspend: debugger/cmds/suspend.md
  - Advanced Topics:
    - Pretty Printers: advanced/pretty_printers.md
    - Wireless Debugging: advanced/wireless.md
  - Engineering:
    - Debug Server:
      - Stack traces: debug_server/stack.md
      - Exposed memory: debug_server/exposed_memory.md
    - Debugger:
      - Comms server: debugger/comms.md
    - Protocol Documentation:
      - V1 (Current): protocol/v1.md

theme:
  name: material
  font:
    code: JetBrains Mono
  icon:
    logo: material/bug
  palette:
    primary: black
    scheme: slate
  features:
    - navigation.tabs
    - navigation.path
    - content.code.copy
    - navigation.top
    - content.code.annotate
    - toc.integrate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
